version: 2
jobs:
  build:
    working_directory: /go/src/github.com/ut0mt8/k8s_external_lb
    docker:
      - image: circleci/golang:1.10.0

    steps:
      - checkout
      - run:
          name: Get and compile dependancies
          command: go get -t -d -v ./...
      - run:
          name: Compile main program
          command: go get 
      - store_artifacts:
          path: /go/bin
          destination: raw-bin
